apiVersion: v1
kind: ReplicationController
metadata:
  name: tomcate
spec:
  replicas: 2
  selector:
    app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
        - name: mytomcatcont
          image: tomcate
          ports:
            - containerPort: 80
