apiVersion: v1
kind: Service
metadata:
  name: mytomcat-sc
  labels: 
    app: mytomcat
spec: 
  type: NodePort
  ports:
  - port: 80
    nodePort: 30002
    protocol: TCP
  selector:
    app: mytomcat
