apiVersion: v1
kind: Service
metadata:
  name: venkey-svc
  labels: 
    app: mynginx
spec: 
  type: NodePort
  ports:
  - port: 80
    nodeport: 30001
    protocall: TCP
  selector:
    app: mynginx
